FROM mcr.microsoft.com/vscode/devcontainers/python:3.10

RUN pip install \
    ipywidgets \
    jupyter \
    gymnasium \
    moviepy \
    numpy==1.26.4 \
    pandas \
    plotly \
    polygon-api-client \
    pygame \
    stable-baselines3 \
    scikit-learn \
    tensorboard \
    wandb

EXPOSE 8888
