FROM mcr.microsoft.com/vscode/devcontainers/python:3.10

RUN pip install \
    numpy==1.26.4 \
    matplotlib \
    gymnasium \
    plotly \
    pandas \
    wandb \
    jupyter \
    seaborn \
    scipy \
    statsmodels \
    sktime \ 
    darts \ 
    yfinance \
    cpi \
    binance \
    nasdaq-data-link \
    arch

EXPOSE 8888
